var leftJson =[{
    id:'lfn_01',
    pid:'null',
    name:'首页',
    icon:'i_home',
    linkPath:'home/home.html'
  },{
    id:'lfn_02',
    pid:'null',
    name:'通知公告',
    icon:'i_notice',
    linkPath:'notice/notice.html'
  },{
    id:'lfn_16',
    pid:'null',
    name:'信息公示',
    icon:'i_info',
    linkPath:'infopublic/info.html'
  },{
    id:'lfn_03',
    pid:'null',
    name:'数据导入',
    icon:'i_import',
    linkPath:'import/import.html'
  },{
    id:'lfn_04',
    pid:'lfn_04',
    name:'进货管理',
    icon:'i_stock',
    linkPath:'javascript:void(0);'
  },{
    id:'lfn_04_01',
    pid:'lfn_04',
    name:'采购品',
    icon:'null',
    linkPath:'replenish/purchased/purchased.html'
  },{
    id:'lfn_04_02',
    pid:'lfn_04',
    name:'供应商管理',
    icon:'null',
    linkPath:'replenish/supplier/supplier.html'
  },{
    id:'lfn_04_03',
    pid:'lfn_04',
    name:'新增进货',
    icon:'null',
    linkPath:'replenish/into/into.html'
  },{
    id:'lfn_04_04',
    pid:'lfn_04',
    name:'自动收货',
    icon:'null',
    linkPath:'replenish/automatic/automatic.html'
  },{
    id:'lfn_04_05',
    pid:'lfn_04',
    name:'近期进货维护',
    icon:'null',
    linkPath:'replenish/near/near.html'
  },{
    id:'lfn_04_06',
    pid:'lfn_04',
    name:'历史进货查询',
    icon:'null',
    linkPath:'replenish/near/near.html'
  },{
    id:'lfn_04_07',
    pid:'lfn_04',
    name:'票据管理',
    icon:'null',
    linkPath:'replenish/paper/paper.html'
  },{
    id:'lfn_05',
    pid:'null',
    name:'配送管理',
    icon:'i_distrib',
    linkPath:'javascript:void(0);'
  },{
    id:'lfn_05_01',
    pid:'lfn_05',
    name:'产出品',
    icon:'null',
    linkPath:'distribute/output/output.html'
  },{
    id:'lfn_05_02',
    pid:'lfn_05',
    name:'收货商管理',
    icon:'null',
    linkPath:'distribute/goods/goods.html'
  },{
    id:'lfn_05_03',
    pid:'lfn_05',
    name:'新增发货',
    icon:'null',
    linkPath:'distribute/send/send.html'
  },{
    id:'lfn_05_04',
    pid:'lfn_05',
    name:'近期发货维护',
    icon:'null',
    linkPath:'distribute/near/near.html'
  },{
    id:'lfn_05_05',
    pid:'lfn_05',
    name:'历史发货查询',
    icon:'null',
    linkPath:'distribute/history/history.html'
  },{
    id:'lfn_06',
    pid:'null',
    name:'废弃物回收',
    icon:'i_recyc',
    linkPath:'javascript:void(0);'
  },{
    id:'lfn_06_01',
    pid:'lfn_06',
    name:'废弃油脂',
    icon:'null',
    linkPath:'recycle/oil/oil.html'
  },{
    id:'lfn_06_02',
    pid:'lfn_06',
    name:'餐厨垃圾',
    icon:'null',
    linkPath:'recycle/kitchen/kitchen.html'
  },{
    id:'lfn_06_03',
    pid:'lfn_06',
    name:'回收单位管理',
    icon:'null',
    linkPath:'recycle/unit/unit.html'
  },{
    id:'lfn_07',
    pid:'null',
    name:'门店管理',
    icon:'i_chain',
    linkPath:'javascript:void(0);'
  },{
    id:'lfn_07_01',
    pid:'lfn_07',
    name:'门店管理',
    icon:'null',
    linkPath:'chain/mainten/mainten-start.html'
  },{
    id:'lfn_07_02',
    pid:'lfn_07',
    name:'门店台账录入统计',
    icon:'null',
    linkPath:'chain/statis/statis.html'
  },{
    id:'lfn_08',
    pid:'null',
    name:'留样登记',
    icon:'i_samples',
    linkPath:'samples/samples.html'
  },{
    id:'lfn_09',
    pid:'null',
    name:'团膳外卖登记',
    icon:'i_meals',
    linkPath:'meals/meals.html'
  },{
    id:'lfn_10',
    pid:'null',
    name:'大型宴会申报',
    icon:'i_banquet',
    linkPath:'banquet/banquet.html'
  },{
    id:'lfn_11',
    pid:'null',
    name:'从业人员',
    icon:'i_employ',
    linkPath:'employ/employ.html'
  },{
    id:'lfn_12',
    pid:'null',
    name:'数据统计',
    icon:'i_data',
    linkPath:'javascript:void(0);'
  },{
    id:'lfn_12_01',
    pid:'lfn_12',
    name:'进货统计',
    icon:'null',
    linkPath:'datastatis/replenish/supplier.html'
  },{
    id:'lfn_12_02',
    pid:'lfn_12',
    name:'进货对账',
    icon:'null',
    linkPath:'datastatis/replenish/init.html'
  },{
    id:'lfn_12_03',
    pid:'lfn_12',
    name:'发货统计',
    icon:'null',
    linkPath:'datastatis/delivery/goods.html'
  },{
    id:'lfn_12_04',
    pid:'lfn_12',
    name:'发货对账',
    icon:'null',
    linkPath:'datastatis/delivery/init.html'
  },{
    id:'lfn_13',
    pid:'null',
    name:'预警提示',
    icon:'i_warning',
    linkPath:'javascript:void(0);'
  },{
    id:'lfn_13_01',
    pid:'lfn_13',
    name:'人员预警',
    icon:'null',
    linkPath:'warning/personnel/personnel-health.html'
  },{
    id:'lfn_13_02',
    pid:'lfn_13',
    name:'证照预警',
    icon:'null',
    linkPath:'warning/licenses/licenses.html'
  },{
    id:'lfn_13_03',
    pid:'lfn_13',
    name:'台账预警',
    icon:'null',
    linkPath:'warning/parameter/parameter.html'
  },{
    id:'lfn_13_04',
    pid:'lfn_13',
    name:'温湿度预警',
    icon:'null',
    linkPath:'warning/temhum/temhum.html'
  /*},{
    id:'lfn_14',
    pid:'null',
    name:'温湿度监控',
    icon:'i_monitor',
    linkPath:'monitor/monitor.html'*/
  },{
    id:'lfn_15',
    pid:'null',
    name:'系统管理',
    icon:'i_customer',
    linkPath:'javascript:void(0);'
  },{
    id:'lfn_15_01',
    pid:'lfn_15',
    name:'用户管理',
    icon:'null',
    linkPath:'system/user/user.html'
  },{
    id:'lfn_15_02',
    pid:'lfn_15',
    name:'企业信息',
    icon:'null',
    linkPath:'system/account/account-view.html'
  },{
    id:'lfn_15_03',
    pid:'lfn_15',
    name:'个人中心',
    icon:'null',
    linkPath:'system/personal/personal.html'
}];

function navLeft(data){
   $('.lf_navs').empty();
   var objNav= eval(data);
   for(var i = 0,len = objNav.length; i< len; i++){
     var navL ='<dt id="'+ objNav[i].id +'_dt"><a href="'+ objNav[i].linkPath +'" target="'+ objNav[i].id +'" id="'+ objNav[i].id +'"><i class="'+ objNav[i].icon +'"></i><span>'+ objNav[i].name +'</span></a></dt><dd  id="'+objNav[i].id+'_dd"></dd>';//一级菜单   
     //console.log(JSON.stringify(objNav[i].pid));
     if(objNav[i].pid != 'null' && objNav[i].pid != null && objNav[i].pid != "" && $("#"+objNav[i].pid).length > 0){     
        var subL ='<a id="'+ objNav[i].id +'" href="'+ objNav[i].linkPath +'" title="'+objNav[i].name+'" target="'+objNav[i].id+'"><i class="i_arrow"></i><span>'+ objNav[i].name +'</span></a>';//二级菜单
            if($('#'+objNav[i].pid+'_dd').length > 0){
               $('#'+objNav[i].pid+'_dd').append(subL);//添加二级(json数组二级id匹配一级的pid)
            }         
       }else{
         $('.lf_navs').append(navL);//添加一级
     }
   }
   return false;
}